/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary":                "#70d4ef",
        "primary-teal":           "#0b8da6",
        "primary-teal-dim":       "#00687b",
        "primary-container":      "#2e9db7",
        "on-primary":             "#003641",
        "on-primary-fixed":       "#001f26",
        "on-primary-fixed-variant":"#004e5d",
        "primary-fixed":          "#aeecff",
        "primary-fixed-dim":      "#70d4ef",
        "inverse-primary":        "#00687b",
        "surface":                "#0f1416",
        "surface-dim":            "#0f1416",
        "surface-bright":         "#353a3c",
        "surface-container-lowest":"#0a0f11",
        "surface-container-low":  "#171c1e",
        "surface-container":      "#1b2022",
        "surface-container-high": "#262b2d",
        "surface-container-highest":"#303637",
        "surface-variant":        "#303637",
        "surface-tint":           "#70d4ef",
        "on-surface":             "#dfe3e5",
        "on-surface-variant":     "#bdc8cc",
        "on-background":          "#dfe3e5",
        "background":             "#0f1416",
        "inverse-surface":        "#dfe3e5",
        "inverse-on-surface":     "#2c3133",
        "outline":                "#879396",
        "outline-variant":        "#3e484c",
        "secondary":              "#c0c6db",
        "secondary-container":    "#404758",
        "secondary-fixed":        "#dce2f7",
        "secondary-fixed-dim":    "#c0c6db",
        "on-secondary":           "#293040",
        "on-secondary-container": "#aeb5c9",
        "on-secondary-fixed":     "#141b2b",
        "on-secondary-fixed-variant":"#404758",
        "tertiary":               "#efc200",
        "tertiary-container":     "#cea700",
        "tertiary-fixed":         "#ffe083",
        "tertiary-fixed-dim":     "#eec200",
        "on-tertiary":            "#3c2f00",
        "on-tertiary-container":  "#4e3e00",
        "on-tertiary-fixed":      "#231b00",
        "on-tertiary-fixed-variant":"#574500",
        "error":                  "#ffb4ab",
        "error-container":        "#93000a",
        "on-error":               "#690005",
        "on-error-container":     "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm:      "0.25rem",
        lg:      "0.75rem",
        xl:      "1rem",
        "2xl":   "1.5rem",
        "3xl":   "2rem",
        "4xl":   "2.5rem",
        "5xl":   "3rem",
        full:    "9999px",
      },
      spacing: {
        "section-gap-desktop": "120px",
        "section-gap-mobile":  "64px",
        "container-max":       "1280px",
        "margin-desktop":      "48px",
        "margin-mobile":       "20px",
        "gutter":              "24px",
        "base":                "8px",
      },
      fontFamily: {
        "display":    ["Poetsen One", "sans-serif"],
        "body":       ["Poltawski Nowy", "serif"],
        "label":      ["Pontano Sans", "sans-serif"],
        // legacy token aliases
        "display-lg": ["Poetsen One", "sans-serif"],
        "display-md": ["Poetsen One", "sans-serif"],
        "body-lg":    ["Poltawski Nowy", "serif"],
        "body-md":    ["Poltawski Nowy", "serif"],
        "label-sm":   ["Pontano Sans", "sans-serif"],
        "headline-lg":["Poetsen One", "sans-serif"],
        "headline-lg-mobile":["Poetsen One", "sans-serif"],
      },
      fontSize: {
        "display-lg":       ["72px",  { lineHeight:"1.1",  letterSpacing:"-0.02em", fontWeight:"400" }],
        "display-md":       ["48px",  { lineHeight:"1.2",  letterSpacing:"0em",     fontWeight:"400" }],
        "headline-lg":      ["32px",  { lineHeight:"1.3",  fontWeight:"400" }],
        "headline-lg-mobile":["28px", { lineHeight:"1.3",  fontWeight:"400" }],
        "body-lg":          ["18px",  { lineHeight:"1.6",  fontWeight:"400" }],
        "body-md":          ["16px",  { lineHeight:"1.6",  fontWeight:"400" }],
        "label-sm":         ["12px",  { lineHeight:"1",    letterSpacing:"0.1em", fontWeight:"600" }],
      },
      animation: {
        "marquee":       "marquee 32s linear infinite",
        "pulse-glow":    "pulse-glow 3s ease-in-out infinite",
        "float-y":       "float-y 4s ease-in-out infinite",
        "float-y-slow":  "float-y 6s ease-in-out infinite",
        "scan-line":     "scan-line 5s linear infinite",
        "border-pulse":  "border-pulse 2.5s ease-in-out infinite",
      },
      keyframes: {
        marquee:      { "0%":{ transform:"translateX(0)" }, "100%":{ transform:"translateX(-50%)" } },
        "pulse-glow": { "0%,100%":{ opacity:"0.5", transform:"scale(1)" }, "50%":{ opacity:"1", transform:"scale(1.15)" } },
        "float-y":    { "0%,100%":{ transform:"translateY(0)" }, "50%":{ transform:"translateY(-10px)" } },
        "scan-line":  { "0%":{ transform:"translateY(-100%)" }, "100%":{ transform:"translateY(200%)" } },
        "border-pulse":{"0%,100%":{ borderColor:"rgba(11,141,166,0.3)" }, "50%":{ borderColor:"rgba(11,141,166,0.8)" } },
      },
    },
  },
  plugins: [],
};
