/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
          "primary-container": "#2e9db7",
          "on-tertiary-fixed": "#231b00",
          "on-secondary-fixed": "#141b2b",
          "surface-container-high": "#262b2d",
          "secondary-fixed": "#dce2f7",
          "primary": "#70d4ef",
          "on-tertiary-container": "#4e3e00",
          "secondary-fixed-dim": "#c0c6db",
          "secondary-container": "#404758",
          "on-tertiary": "#3c2f00",
          "secondary": "#c0c6db",
          "primary-fixed": "#aeecff",
          "on-secondary-fixed-variant": "#404758",
          "on-background": "#dfe3e5",
          "tertiary-fixed": "#ffe083",
          "tertiary-container": "#cea700",
          "primary-fixed-dim": "#70d4ef",
          "on-tertiary-fixed-variant": "#574500",
          "surface-container-low": "#171c1e",
          "on-secondary-container": "#aeb5c9",
          "surface-variant": "#303637",
          "surface-container-lowest": "#0a0f11",
          "inverse-surface": "#dfe3e5",
          "error-container": "#93000a",
          "surface-tint": "#70d4ef",
          "surface-dim": "#0f1416",
          "surface": "#0f1416",
          "outline": "#879396",
          "inverse-primary": "#00687b",
          "surface-container": "#1b2022",
          "on-primary-fixed": "#001f26",
          "surface-container-highest": "#303637",
          "on-surface": "#dfe3e5",
          "surface-bright": "#353a3c",
          "tertiary-fixed-dim": "#eec200",
          "tertiary": "#efc200",
          "on-secondary": "#293040",
          "on-error-container": "#ffdad6",
          "error": "#ffb4ab",
          "outline-variant": "#3e484c",
          "on-primary-container": "#002e38",
          "on-error": "#690005",
          "on-primary-fixed-variant": "#004e5d",
          "inverse-on-surface": "#2c3133",
          "background": "#0f1416",
          "on-surface-variant": "#bdc8cc",
          "on-primary": "#003641"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "section-gap-desktop": "120px",
          "container-max": "1280px",
          "margin-mobile": "20px",
          "base": "8px",
          "section-gap-mobile": "64px",
          "margin-desktop": "48px",
          "gutter": "24px"
      },
      "fontFamily": {
          "body-lg": ["Poltawski Nowy"],
          "display-lg": ["Poetsen One"],
          "display-md": ["Poetsen One"],
          "label-sm": ["Pontano Sans"],
          "headline-lg-mobile": ["Poetsen One"],
          "headline-lg": ["Poetsen One"],
          "body-md": ["Poltawski Nowy"]
      },
      "fontSize": {
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "display-lg": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400"}],
          "display-md": ["48px", {"lineHeight": "1.2", "letterSpacing": "0em", "fontWeight": "400"}],
          "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
          "headline-lg-mobile": ["28px", {"lineHeight": "1.3", "fontWeight": "400"}],
          "headline-lg": ["32px", {"lineHeight": "1.3", "fontWeight": "400"}],
          "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
